before_script:
  -  if [ ! -d ~/.rbenv ]; then 
  -    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  -    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  -    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  -    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  -    . ~/.bash_profile
  -  fi
  - rbenv global 2.1.8 || rbenv install 2.1.8 && rbenv global 2.1.8
  - gem install bundle
  - bundle install

stages:
  - lint
  - parser
  - rspec
  - acceptance

lint:
  stage: lint
  script:
    - bundle exec rake lint
  only:
    - master

parser:
  stage: parser
  script:
    - bundle exec rake syntax
  only:
    - master

rspec:
  stage: rspec
  script:
    - bundle exec rake spec
  only:
    - master

acceptance_ubuntu:
  stage: acceptance
  script:
    - bundle exec rake beaker
  only:
    - master

acceptance_centos:
  stage: acceptance
  script:
    - export BEAKER_set=centos-6
    - bundle exec rake beaker
  only:
    - master
