HOSTS:
  ubuntu-14-04-x64:
    roles:
      - master
    platform: ubuntu-14.04-amd64
    image : ubuntu:14.04
    docker_preserve_image: true
    hypervisor : docker
  fedora-23-x64:
    roles:
      - agent
    platform: fedora-23-x86_64
    image : fedora:23
    docker_preserve_image: true
    hypervisor : docker
CONFIG:
  log_level: debug
  type: git
