HOSTS:
  ubuntu-14-04-x64:
    roles:
      - master
      - database
      - dashboard
    platform: ubuntu-14.04-amd64
    image : ubuntu:14.04
    docker_preserve_image: true
    docker_image_commands:
      - 'locale-gen en_US.UTF-8'
      - 'export LANG=en_US.UTF-8'
      - 'export LANGUAGE=en_US:en' 
      - 'export LC_ALL=en_US.UTF-8'
    hypervisor : docker
    ip: '10.255.33.135'
  ubuntu-1404-agent-x64:
    roles:
      - default
      - frictionless
    platform: ubuntu-14.04-x64
    image : ubuntu:14.04
    docker_image_commands:
      - 'locale-gen en_US.UTF-8'
      - 'export LANG=en_US.UTF-8'
      - 'export LANGUAGE=en_US:en' 
      - 'export LC_ALL=en_US.UTF-8'
    hypervisor : docker
    ip: '10.255.33.129'
CONFIG:
  log_level: debug
  type: pe
